spring:
  datasource:
    url: jdbc:mysql://localhost:21446/zoo
    username: amidman
    password: sadlfjqweoirjjalsdkfn
    tomcat:
      max-wait: 10000
      max-active: 50
      test-on-borrow: true
server:
  port: 2134
springdoc:
  api-docs:
    path: /swagger
  swagger-ui:
    path: /swagger/ui/index.html
